server:
  port: 8010
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
        service: customer-message-service
    alibaba:
      seata:
        tx-service-group: hs_store_group
  application:
    name: customer-message-service

mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    io:
      seata: info

dubbo:
  protocol: # name:采用的协议名称 port:-1代表自动选择端口
    port: -1
    name: dubbo
  scan: # dubbo服务路径
    base-packages: com.hs.storemessage.service
  application:
    qos-enable: false #关闭dubbo在线运维工具
  registry:
    address: spring-cloud://localhost #挂载到SpringCloud注册中心
  cloud:
    subscribed-services: / #订阅的服务名称，默认订阅所有服务，provider无须订阅服务所以配置为