server:
  port: 8110
spring:
  application:
    name: store-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hs_tx_group
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
        service: store-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/customer_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000

dubbo:
  protocol: # name:采用的协议名称 port:-1代表自动选择端口
    port: -1
    name: dubbo
  application:
    name: store-order-service #注册服务名称
    qos-enable: false #关闭dubbo在线运维工具
  registry:
    address: nacos://192.168.195.129:80 #挂载到Nacos注册中心
  cloud:
    subscribed-services: customer-account-service,store-storage-service #订阅的服务名称，默认订阅所有服务，provider无须订阅服务所以配置为

logging:
  level:
    io:
      seata: info
