server:
  port: 8200
spring:
  application:
    name: store-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hs_tx_group
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
        service: store-storage-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/store_storage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000
dubbo:
  protocol: # name:采用的协议名称 port:-1代表自动选择端口
    port: -1
    name: dubbo
  scan: # dubbo服务路径
    base-packages: com.hs.service
  application:
    name: store-storage-service #注册服务名称
    qos-enable: false #关闭dubbo在线运维工具
  registry:
    address: nacos://192.168.195.129:80 #挂载到Nacos注册中心
  cloud:
    subscribed-services: / #订阅的服务名称，默认订阅所有服务，provider无须订阅服务所以配置为
logging:
  level:
    io:
      seata: info
